export type SkillEndpointTier = 'public' | 'alternative' | 'unstructured';

export interface SkillEndpointMetadata {
  skill: string;
  file: string;
  method: string;
  path: string;
  tier: SkillEndpointTier;
  required_subscription_tier: 'free' | 'pro';
  access: 'free_and_pro' | 'pro_only';
  pro_required: boolean;
}

const SKILL_ENDPOINT_METADATA: SkillEndpointMetadata[] = [
  {
    skill: 'arrays-data-api-spot-market-price-and-volume',
    file: 'crypto-detail',
    method: 'GET',
    path: '/api/v1/crypto/detail',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'fear-greed-index',
    method: 'GET',
    path: '/api/v1/crypto/fear-greed-index',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-futures-data',
    file: 'funding-rate',
    method: 'GET',
    path: '/api/v1/crypto/funding-rate',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-spot-market-price-and-volume',
    file: 'crypto-futures-ohlcv',
    method: 'GET',
    path: '/api/v1/crypto/futures/ohlcv',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-spot-market-price-and-volume',
    file: 'crypto-kline',
    method: 'GET',
    path: '/api/v1/crypto/kline',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'list',
    method: 'GET',
    path: '/api/v1/crypto/list',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-futures-data',
    file: 'long-short-ratio',
    method: 'GET',
    path: '/api/v1/crypto/long-short-ratio',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'crypto-market-cap',
    method: 'GET',
    path: '/api/v1/crypto/market-cap',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'market-metrics',
    method: 'GET',
    path: '/api/v1/crypto/market-metrics',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-spot-market-price-and-volume',
    file: 'crypto-ohlcv',
    method: 'GET',
    path: '/api/v1/crypto/ohlcv',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-futures-data',
    file: 'open-interest',
    method: 'GET',
    path: '/api/v1/crypto/open-interest',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'screener-metrics',
    method: 'GET',
    path: '/api/v1/crypto/screener/metrics',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'screener-metrics-timerange',
    method: 'GET',
    path: '/api/v1/crypto/screener/metrics/timerange',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'trading-pair',
    method: 'GET',
    path: '/api/v1/crypto/trading-pair',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-etf-fundamentals',
    file: 'country-weightings',
    method: 'GET',
    path: '/api/v1/etf/country-weightings',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-etf-fundamentals',
    file: 'holdings',
    method: 'GET',
    path: '/api/v1/etf/holdings',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-etf-fundamentals',
    file: 'info',
    method: 'GET',
    path: '/api/v1/etf/info',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-etf-fundamentals',
    file: 'sector-weightings',
    method: 'GET',
    path: '/api/v1/etf/sector-weightings',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'macro-commodity-historical',
    method: 'GET',
    path: '/api/v1/macro/commodity/historical',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'macro-commodity-real-time',
    method: 'GET',
    path: '/api/v1/macro/commodity/real-time',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'macro-commodity-symbol-list',
    method: 'GET',
    path: '/api/v1/macro/commodity/symbols',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'economic-indicators',
    method: 'GET',
    path: '/api/v1/macro/economic-indicators',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'macro-forex-historical',
    method: 'GET',
    path: '/api/v1/macro/forex/historical',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'macro-forex-real-time',
    method: 'GET',
    path: '/api/v1/macro/forex/real-time',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'macro-forex-symbol-list',
    method: 'GET',
    path: '/api/v1/macro/forex/symbols',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'macro-index-historical',
    method: 'GET',
    path: '/api/v1/macro/index/historical',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'macro-index-real-time',
    method: 'GET',
    path: '/api/v1/macro/index/real-time',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-macro-and-economics',
    file: 'rates',
    method: 'GET',
    path: '/api/v1/macro/treasury-rates',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'company-balance-sheets',
    method: 'GET',
    path: '/api/v1/stocks/company/balance-sheets',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'company-cashflow-statements',
    method: 'GET',
    path: '/api/v1/stocks/company/cashflow-statements',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'company-detail',
    method: 'GET',
    path: '/api/v1/stocks/company/detail',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'company-income-statements',
    method: 'GET',
    path: '/api/v1/stocks/company/income-statements',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'company-kpi',
    method: 'GET',
    path: '/api/v1/stocks/company/kpi',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'crowdfunding-offerings',
    method: 'GET',
    path: '/api/v1/stocks/crowdfunding/offerings',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'dividends',
    method: 'GET',
    path: '/api/v1/stocks/dividends',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'earnings-calendar',
    method: 'GET',
    path: '/api/v1/stocks/earnings-calendar',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'equity-offering',
    method: 'GET',
    path: '/api/v1/stocks/equity-offering',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-metrics',
    file: 'financial-metrics',
    method: 'GET',
    path: '/api/v1/stocks/financial-metrics',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'fiscal-dates',
    method: 'GET',
    path: '/api/v1/stocks/fiscal-dates',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'fiscal-dates-range',
    method: 'GET',
    path: '/api/v1/stocks/fiscal-dates/range',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'ipo-calendar',
    method: 'GET',
    path: '/api/v1/stocks/ipo-calendar',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'ipo-confirmed-calendar',
    method: 'GET',
    path: '/api/v1/stocks/ipo-confirmed-calendar',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-spot-market-price-and-volume',
    file: 'stocks-kline',
    method: 'GET',
    path: '/api/v1/stocks/kline',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-metrics',
    file: 'market-metrics',
    method: 'GET',
    path: '/api/v1/stocks/market-metrics',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'mergers-acquisitions',
    method: 'GET',
    path: '/api/v1/stocks/mergers-acquisitions',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'outstanding-shares',
    method: 'GET',
    path: '/api/v1/stocks/outstanding-shares',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-metrics',
    file: 'ratings',
    method: 'GET',
    path: '/api/v1/stocks/ratings',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-screener',
    file: 'basic-info-screener',
    method: 'GET',
    path: '/api/v1/stocks/screener/basic-info/{sub}',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-screener',
    file: 'event-screener',
    method: 'GET',
    path: '/api/v1/stocks/screener/events',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-screener',
    file: 'screener-financial-metrics',
    method: 'GET',
    path: '/api/v1/stocks/screener/financial-metrics',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-screener',
    file: 'screener-financial-metrics-timerange',
    method: 'GET',
    path: '/api/v1/stocks/screener/financial-metrics/timerange',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-screener',
    file: 'screener-technical-metrics',
    method: 'GET',
    path: '/api/v1/stocks/screener/technical-metrics',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-stock-screener',
    file: 'screener-technical-metrics-timerange',
    method: 'GET',
    path: '/api/v1/stocks/screener/technical-metrics/timerange',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'sec-earnings-release',
    method: 'GET',
    path: '/api/v1/stocks/sec-earnings-release',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'shares-float',
    method: 'GET',
    path: '/api/v1/stocks/shares-float',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'splits',
    method: 'GET',
    path: '/api/v1/stocks/splits',
    tier: 'public',
    required_subscription_tier: 'free',
    access: 'free_and_pro',
    pro_required: false,
  },
  {
    skill: 'arrays-data-api-crypto-exchange-flow',
    file: 'exchange-flows',
    method: 'GET',
    path: '/api/v1/crypto/exchange-flows',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-company-crypto-holdings',
    file: 'crypto-holdings',
    method: 'GET',
    path: '/api/v1/crypto/holdings',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-inflow-cdd',
    method: 'GET',
    path: '/api/v1/crypto/metrics/inflow-cdd',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-leverage-ratio',
    method: 'GET',
    path: '/api/v1/crypto/metrics/leverage-ratio',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-miner-to-exchange',
    method: 'GET',
    path: '/api/v1/crypto/metrics/miner-to-exchange',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-mvrv',
    method: 'GET',
    path: '/api/v1/crypto/metrics/mvrv',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-nupl',
    method: 'GET',
    path: '/api/v1/crypto/metrics/nupl',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-puell-multiple',
    method: 'GET',
    path: '/api/v1/crypto/metrics/puell-multiple',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-realized-price',
    method: 'GET',
    path: '/api/v1/crypto/metrics/realized-price',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-sopr',
    method: 'GET',
    path: '/api/v1/crypto/metrics/sopr',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-ssr',
    method: 'GET',
    path: '/api/v1/crypto/metrics/ssr',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'metrics-whale-ratio',
    method: 'GET',
    path: '/api/v1/crypto/metrics/whale-ratio',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'crypto-supply',
    method: 'GET',
    path: '/api/v1/crypto/supply',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-futures-data',
    file: 'taker-buy-sell-volume',
    method: 'GET',
    path: '/api/v1/crypto/taker-buy-sell-volume',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-crypto-metrics-and-screener',
    file: 'unlock-events',
    method: 'GET',
    path: '/api/v1/crypto/unlock-events',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-etf-fundamentals',
    file: 'flow',
    method: 'GET',
    path: '/api/v1/etf/flow',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-options',
    file: 'contracts',
    method: 'GET',
    path: '/api/v1/options/contracts',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-options',
    file: 'kline',
    method: 'GET',
    path: '/api/v1/options/kline',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-fundamentals',
    file: 'company-executives',
    method: 'GET',
    path: '/api/v1/stocks/company/executives',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-estimates-and-targets',
    file: 'company-price-target-consensus',
    method: 'GET',
    path: '/api/v1/stocks/company/price-target-consensus',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-estimates-and-targets',
    file: 'company-price-target-news',
    method: 'GET',
    path: '/api/v1/stocks/company/price-target-news',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-estimates-and-targets',
    file: 'company-price-target-summary',
    method: 'GET',
    path: '/api/v1/stocks/company/price-target-summary',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-ownership-and-flow',
    file: 'congress-recent-trades',
    method: 'GET',
    path: '/api/v1/stocks/congress/recent-trades',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-stock-metrics',
    file: 'darkpool',
    method: 'GET',
    path: '/api/v1/stocks/darkpool',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-estimates-and-targets',
    file: 'estimates-guidance',
    method: 'GET',
    path: '/api/v1/stocks/estimates-guidance',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-ownership-and-flow',
    file: 'insider-transactions',
    method: 'GET',
    path: '/api/v1/stocks/insider/transactions',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-ownership-and-flow',
    file: 'institution-holder',
    method: 'GET',
    path: '/api/v1/stocks/institution-holder',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'activity',
    method: 'GET',
    path: 'polymarket:/activity',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'book',
    method: 'GET',
    path: 'polymarket:/book',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'closed-positions',
    method: 'GET',
    path: 'polymarket:/closed-positions',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'events',
    method: 'GET',
    path: 'polymarket:/events',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'holders',
    method: 'GET',
    path: 'polymarket:/holders',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'markets',
    method: 'GET',
    path: 'polymarket:/markets',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'midpoint',
    method: 'GET',
    path: 'polymarket:/midpoint',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'oi',
    method: 'GET',
    path: 'polymarket:/oi',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'positions',
    method: 'GET',
    path: 'polymarket:/positions',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'price',
    method: 'GET',
    path: 'polymarket:/price',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'prices-history',
    method: 'GET',
    path: 'polymarket:/prices-history',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'public-search',
    method: 'GET',
    path: 'polymarket:/public-search',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'series',
    method: 'GET',
    path: 'polymarket:/series',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'sports',
    method: 'GET',
    path: 'polymarket:/sports',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'spread',
    method: 'GET',
    path: 'polymarket:/spread',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'tags',
    method: 'GET',
    path: 'polymarket:/tags',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'trades',
    method: 'GET',
    path: 'polymarket:/trades',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-polymarket',
    file: 'value',
    method: 'GET',
    path: 'polymarket:/value',
    tier: 'alternative',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-equity-events',
    file: 'earnings-transcript',
    method: 'GET',
    path: '/api/v1/stocks/earnings-transcript',
    tier: 'unstructured',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
  {
    skill: 'arrays-data-api-news',
    file: 'market-news',
    method: 'GET',
    path: '/api/v1/stocks/market-news',
    tier: 'unstructured',
    required_subscription_tier: 'pro',
    access: 'pro_only',
    pro_required: true,
  },
];

export function getSkillEndpointMetadata(
  skill: string,
  file: string
): SkillEndpointMetadata | undefined {
  return SKILL_ENDPOINT_METADATA.find(
    (item) => item.skill === skill && item.file === file
  );
}

export function listSkillEndpointMetadata(
  skill: string
): SkillEndpointMetadata[] {
  return SKILL_ENDPOINT_METADATA.filter((item) => item.skill === skill);
}

export function countSkillEndpointMetadata(): Record<
  SkillEndpointTier,
  number
> {
  return { public: 56, alternative: 45, unstructured: 2 };
}
