// THIS FILE IS GENERATED by scripts/vendor-contract.ts at build time.
// Edit design-contract.yaml in the skills repo, not this file.
export const FALLBACK_CONTRACT_YAML: string = `version: 1
description: "Permissive bundled fallback used when the design-contract CDN is unavailable."
global:
  required-container:
    selector: ".playbook-container"
    must-exist: false
  scroll:
    sole-scroll-container: ["body"]
  typography:
    font-family-root-must-include: ""
    font-weight-allowed: [100, 200, 300, 400, 500, 600, 700, 800, 900]
  links:
    anchor-required-attrs: []
components: {}
`;
