// scripts/vendor-contract.ts
// Build-time vendoring of the canonical design-system artifacts.
// Fetches the contract YAML and the v1 CSS bundle from the CDN, embeds them
// into generated source files (fallback-contract.ts, fallback-bundle.ts),
// then verifies that the bundle delivers the root font-family the contract
// promises — so the linter's auto-pass on canonical-bundle <link>s is
// actually justified at npm-publish time.
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import * as csstree from 'css-tree';
import YAML from 'yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CONTRACT_CDN_URL =
  process.env.DESIGN_CONTRACT_URL ??
  'https://alva-ai-static.b-cdn.net/design-system/design-contract.yaml';
const BUNDLE_CDN_URL =
  process.env.DESIGN_BUNDLE_URL ??
  'https://alva-ai-static.b-cdn.net/design-system/v1/design-system.css';

const CONTRACT_OUT = path.resolve(
  __dirname,
  '../src/lint/fallback-contract.ts'
);
const BUNDLE_OUT = path.resolve(__dirname, '../src/lint/fallback-bundle.ts');

async function fetchOrFallback(
  url: string,
  outPath: string,
  exportName: string
): Promise<string> {
  let content = '';
  try {
    const resp = await fetch(url);
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    content = await resp.text();
    console.log(`vendor-contract: fetched ${content.length} bytes from ${url}`);
  } catch (e) {
    console.warn(
      `vendor-contract: CDN fetch failed for ${url} (${(e as Error).message}); keeping existing fallback if any`
    );
    if (fs.existsSync(outPath)) {
      const cur = fs.readFileSync(outPath, 'utf8');
      const m = cur.match(
        new RegExp(`${exportName}:\\s*string\\s*=\\s*\`([\\s\\S]*?)\``)
      );
      if (m) content = m[1]!;
    }
  }
  return content;
}

function emitTsString(
  outPath: string,
  exportName: string,
  value: string
): void {
  const escaped = value
    .replace(/`/g, '\\`')
    .replace(/\\\$\\{/g, '\\\\\\${')
    .replace(/\$\{/g, '\\${');
  const body = `// THIS FILE IS GENERATED by scripts/vendor-contract.ts at build time.
// Edit design-contract.yaml / design.md in the skills repo, not this file.
export const ${exportName}: string = \`${escaped}\`;
`;
  fs.writeFileSync(outPath, body, 'utf8');
  console.log(`vendor-contract: wrote ${outPath}`);
}

const ROOT_SELECTOR_RE = /^(body|html|:root|html\s*,\s*body|body\s*,\s*html)$/i;

function bundleDeliversRootFontFamily(
  bundle: string,
  required: string
): boolean {
  let ast: csstree.CssNode;
  try {
    ast = csstree.parse(bundle);
  } catch {
    return false;
  }
  if (ast.type !== 'StyleSheet') return false;

  let found = false;
  csstree.walk(ast, {
    visit: 'Rule',
    enter(node) {
      if (found) return;
      if (node.type !== 'Rule') return;
      const sel = csstree.generate(node.prelude).trim();
      if (!ROOT_SELECTOR_RE.test(sel)) return;
      csstree.walk(node.block, {
        visit: 'Declaration',
        enter(d) {
          if (found) return;
          if (d.type !== 'Declaration') return;
          if (d.property !== 'font-family') return;
          const val = csstree.generate(d.value).toLowerCase();
          if (val.includes(required.toLowerCase())) found = true;
        },
      });
    },
  });
  return found;
}

interface RawContract {
  global?: {
    typography?: { 'font-family-root-must-include'?: string };
  };
}

function verifyVendoredArtifacts(yaml: string, bundle: string): void {
  // Allow CDN-was-down fallback path with empty content to slip through:
  // if the contract or bundle ended up empty, the existing build will fail
  // later in a more obvious place. Don't double-fail.
  if (!yaml || !bundle) return;

  let parsed: RawContract;
  try {
    parsed = YAML.parse(yaml) as RawContract;
  } catch (e) {
    console.error(
      `vendor-contract: vendored contract is not valid YAML — ${(e as Error).message}`
    );
    process.exit(1);
  }
  const required =
    parsed!.global?.typography?.['font-family-root-must-include'];
  if (!required) return; // contract makes no font-family-root claim

  if (!bundleDeliversRootFontFamily(bundle, required)) {
    console.error(
      `vendor-contract: vendored bundle does not deliver the root font-family the contract requires.`
    );
    console.error(`  contract requires: '${required}' on body/html/:root`);
    console.error(`  bundle (${BUNDLE_CDN_URL}) has no matching rule`);
    console.error(
      `  → fix the source bundle in the skills repo (design.md Typography),`
    );
    console.error(
      `    re-publish the CDN, then re-run prebuild. Set DESIGN_BUNDLE_URL to override the source if needed.`
    );
    process.exit(1);
  }
  console.log(
    `vendor-contract: verified bundle delivers '${required}' as root font-family`
  );
}

async function main() {
  const yaml = await fetchOrFallback(
    CONTRACT_CDN_URL,
    CONTRACT_OUT,
    'FALLBACK_CONTRACT_YAML'
  );
  const bundle = await fetchOrFallback(
    BUNDLE_CDN_URL,
    BUNDLE_OUT,
    'FALLBACK_BUNDLE_CSS'
  );

  emitTsString(CONTRACT_OUT, 'FALLBACK_CONTRACT_YAML', yaml);
  emitTsString(BUNDLE_OUT, 'FALLBACK_BUNDLE_CSS', bundle);

  verifyVendoredArtifacts(yaml, bundle);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
