// scripts/vendor-contract.ts
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CDN_URL =
  process.env.DESIGN_CONTRACT_URL ??
  'https://alva-ai-static.b-cdn.net/design-system/design-contract.yaml';

const OUT = path.resolve(__dirname, '../src/lint/fallback-contract.ts');

async function main() {
  let yaml = '';
  try {
    const resp = await fetch(CDN_URL);
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    yaml = await resp.text();
    console.log(
      `vendor-contract: fetched ${yaml.length} bytes from ${CDN_URL}`
    );
  } catch (e) {
    console.warn(
      `vendor-contract: CDN fetch failed (${(e as Error).message}); keeping existing fallback if any`
    );
    if (fs.existsSync(OUT)) {
      const cur = fs.readFileSync(OUT, 'utf8');
      const m = cur.match(
        /FALLBACK_CONTRACT_YAML:\s*string\s*=\s*`([\s\S]*?)`/
      );
      if (m) yaml = m[1]!;
    }
  }
  const body = `// THIS FILE IS GENERATED by scripts/vendor-contract.ts at build time.
// Edit design-contract.yaml in the skills repo, not this file.
export const FALLBACK_CONTRACT_YAML: string = \`${yaml
    .replace(/`/g, '\\`')
    .replace(/\\\$\\{/g, '\\\\\\${')
    .replace(/\$\{/g, '\\${')}\`;
`;
  fs.writeFileSync(OUT, body, 'utf8');
  console.log(`vendor-contract: wrote ${OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
